//
// Created by szylkret on 2/23/20.
//

#ifndef GBC_EMU_GB_MEM_BLOCK_SIZES_H
#define GBC_EMU_GB_MEM_BLOCK_SIZES_H

#define GB_BLOCKS_NUM 9

#define GB_BANK_0_ADDRESS 0x0000
#define GB_BANK_N_ADDRESS 0x4000
#define GB_VIDEO_RAM_ADDRESS 0x8000
#define GB_EXTERNAL_RAM_ADDRESS 0xa000
#define GB_WORKING_RAM_ADDRESS 0xc000
#define GB_ECHO_RAM_ADDRESS 0xe000
#define GB_SPRITE_INFO_ADDRESS 0xfe00
#define GB_IO_ADDRESS 0xff00
#define GB_HIGH_RAM_ADDRESS 0xff80

//IN BYTES
#define GB_BANK_0_SIZE 2048
#define GB_BANK_N_SIZE 2048
#define GB_VIDEO_RAM_SIZE 1024
#define GB_EXTERNAL_RAM_SIZE 1024
#define GB_WORKING_RAM_SIZE 1024
#define GB_ECHO_RAM_SIZE 960
#define GB_SPRITE_INFO_SIZE 32
#define GB_IO_SIZE 16
#define GB_HIGH_RAM_SIZE 16

#endif //GBC_EMU_GB_MEM_BLOCK_SIZES_H
